name: test-feature

description: Test feature

inputs:
  args:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Setup runner environment
      uses: ./.github/actions/setup-runner-env

    - name: Copy common scripts into features
      uses: ./.github/actions/copy-common-scripts

    - name: Install devcontainers CLI
      uses: ./.github/actions/install-devcontainers-cli

    - if: github.repository == 'rapidsai/devcontainers'
      name: Get AWS credentials for sccache bucket
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-duration-seconds: 3600 # 1 hour
        role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-rapidsai

    - name: Test feature
      shell: bash
      run: devcontainer features test ${{ inputs.args }} ./features;
      env:
        NODE_NO_WARNINGS: 1
        VAULT_S3_TTL: "3600s" # 1 hour

        gh_token: "${{ secrets.WORKFLOW_TOKEN }}"
        vault_host: "${{ secrets.WORKFLOW_TOKEN && 'https://vault.ops.k8s.rapids.ai' || '' }}"
        sccache_bucket_gh: "${{ secrets.WORKFLOW_TOKEN && 'rapids-sccache-devs' || '' }}"
        sccache_region_gh: us-east-2

        aws_session_token: "${{ env.AWS_SESSION_TOKEN || '' }}"
        aws_access_key_id: "${{ env.AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID || '' }}"
        aws_secret_access_key: "${{ env.AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY || '' }}"
        sccache_bucket_ci: "${{ env.AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID && 'rapids-sccache-east' || '' }}"
        sccache_region_ci: us-east-2
