name: test-feature

description: Test feature

inputs:
  args: {type: string, required: true}
  gh_token: {type: string, defaut: '', required: false}
  vault_host: {type: string, defaut: '', required: false}
  rw_sccache_bucket: {type: string, defaut: '', required: false}
  rw_sccache_region: {type: string, defaut: '', required: false}
  ro_sccache_bucket: {type: string, defaut: '', required: false}
  ro_sccache_region: {type: string, defaut: '', required: false}

runs:
  using: composite
  steps:
    - name: Setup runner environment
      uses: ./.github/actions/setup-runner-env

    - name: Copy common scripts into features
      uses: ./.github/actions/copy-common-scripts

    - name: Install devcontainers CLI
      uses: ./.github/actions/install-devcontainers-cli

    - name: Get AWS credentials for sccache bucket
      uses: aws-actions/configure-aws-credentials@v2
      if: github.repository == 'rapidsai/devcontainers'
      with:
        aws-region: us-east-2
        role-duration-seconds: "300" # 5 minutes
        role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-rapidsai

    - name: Test feature
      shell: bash
      run: |
        devcontainer features test ${{ inputs.args }} ./features;
      env:
        NODE_NO_WARNINGS: 1
        VAULT_S3_TTL: "300" # 5 minutes
        gh_token: "${{ inputs.gh_token }}"
        vault_host: "${{ inputs.vault_host }}"
        rw_sccache_bucket: "${{ inputs.rw_sccache_bucket }}"
        rw_sccache_region: "${{ inputs.rw_sccache_region }}"
        ro_sccache_bucket: "${{ inputs.ro_sccache_bucket }}"
        ro_sccache_region: "${{ inputs.ro_sccache_region }}"
