name: image-matrix

description: Determine the image matrix

inputs:
  features:
    type: string
    required: false
  scenarios:
    type: string
    required: false
  full_matrix:
    type: string
    default: 'true'

outputs:
  matrix:
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - id: get-pr-info
      if: inputs.full_matrix != 'true'
      name: Get PR target branch info
      uses: ./.github/actions/get-pr-info

    - name: Check if files changed
      if: inputs.full_matrix != 'true'
      id: changes
      uses: tj-actions/changed-files@v35.4.4
      with:
        base_sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
        files: |
          image/*
          matrix.yml
          .github/workflows/test.yml
          .github/actions/build-image/action.yml
#           .github/actions/image-matrix/action.sh
#           .github/actions/image-matrix/action.yml
#           .github/workflows/build-and-test-image.yml

    - name: Report changes
      if: inputs.full_matrix != 'true'
      shell: bash
      run: echo '${{ toJSON(steps.changes.outputs) }}'

    - name: Determine the image matrix
      id: matrix
      shell: bash
      run: |
        bash --noprofile --norc -x -eo pipefail \
          .github/actions/image-matrix/action.sh \
          '${{ inputs.full_matrix }}' \
          '${{ inputs.features || '[]' }}' \
          '${{ inputs.scenarios || '[]' }}' \
          '${{ steps.changes.outputs.all_changed_and_modified_files }}' \
        | tee -a $GITHUB_OUTPUT;
