name: build-and-push-image

description: Build and push image

inputs:
  dir:
    type: string
    required: true
    description: Image dir
  tag:
    type: string
    required: true
    description: Image tag
  arch:
    type: string
    required: true
    description: Image arch

runs:
  using: composite
  steps:

    - name: Setup runner environment
      uses: ./.github/actions/setup-runner-env

    - name: Copy common scripts into features
      uses: ./.github/actions/copy-common-scripts

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push ghcr.io/${{ github.repository }}:${{ inputs.tag }}-${{ inputs.arch }}
      uses: devcontainers/ci@v0.2
      env:
        NODE_NO_WARNINGS: 1
      with:
        push: always
        skipContainerUserIdUpdate: true
        # Skip setting this so skopeo isn't required
        # platform: linux/${{ inputs.arch }}
        subFolder: images/${{ inputs.dir }}
        imageName: ghcr.io/${{ github.repository }}
        imageTag: ${{ inputs.tag }}-${{ inputs.arch }}
        cacheFrom: ghcr.io/${{ github.repository }}:${{ inputs.tag }}-${{ inputs.arch }}
