name: Build and test devcontainer features

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      args:
        type: string
        required: true

jobs:

  test:
    name: ${{ inputs.name }} (${{ matrix.arch }})
    runs-on: ${{ fromJSON(github.repository != 'rapidsai/devcontainers' && '"ubuntu-latest"' || format('"linux-{0}-cpu4"', matrix.arch)) }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: ${{ inputs.name }}
        uses: ./.github/actions/build-and-test-feature
        with:
          args: "${{ inputs.args }}"
          gh_token: "${{ secrets.WORKFLOW_TOKEN }}"
          vault_host: "${{ secrets.WORKFLOW_TOKEN && 'https://vault.ops.k8s.rapids.ai' || '' }}"
          rw_sccache_bucket: "${{ secrets.WORKFLOW_TOKEN && 'rapids-sccache-devs' || '' }}"
          rw_sccache_region: us-east-2
          ro_sccache_bucket: rapids-sccache-east
          ro_sccache_region: us-east-2
