name: Test

concurrency:
  group: test-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  echo:
    runs-on: ubuntu-latest
    container: {image: "ubuntu:latest"}
    steps:
      - name: echo
        run: |
          echo "${{github.workspace}}"
          echo "${{toJSON(runner)}}"
          echo "${{toJSON(env)}}"
          echo "$(env)"
